version: '3.4'

services: 
  roundbuyapi:
    image: ${DOCKER_REGISTRY-}davithomazellaes/roundbuyapi
    build: 
      context: ../
      dockerfile: TomTec.RoundBuy.API/Dockerfile
    ports:
      - "8001:80"
    depends_on: 
      - sqldata

  sqldata: 
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=RoundBuy@2023
      - ACCEPT_EULA=Y
    volumes:
      - d:/tomtec/dados/volumes/mssql/data:/var/opt/mssql/data
    ports:
      - "1450:1433"